# -*- coding:utf-8 -*- 
# --------------------
# Author:       SDN
# Description:	后台分类
# Time:         2017/3/9
# --------------------
import paging

category_manage = {
    # 首页
    'bar': {
        'category': 'bar',
        'father_category': 'home',
        'table_item': 'item',
        'table_file': 'file',
        'navi_sub': 'home-bar',
        'title_page': '首页管理',
        'items_per_page': paging.manage_home_bar,
        'width_thumb': 200,
        'height_thumb': 200,
        'width_limit': 1920,
        'height_limit': 530,
        'quality_limit': 75,
        'size_limit': 200,
        'compress_type': 1,     # 按宽限压缩
        # 清单页面
        'title_content': 'Banner图片',
        'title_navi1': '首页',
        'title_navi2': 'Banner',
        'url_navi1': '#',
        'url_navi2': '#',
    },
    'service': {
        'category': 'service',
        'father_category': 'home',
        'table_item': 'item',
        'table_file': 'file',
        'navi_sub': 'home-service',
        'title_page': '首页管理',
        'items_per_page': paging.manage_home_service,
        'width_thumb': 200,
        'height_thumb': 200,
        'width_limit': 560,
        'height_limit': 560,
        'quality_limit': 65,
        'size_limit': 100,
        'compress_type': 3,     # 按高限压缩
        # 清单页面
        'title_content': '服务项目',
        'title_navi1': '首页',
        'title_navi2': '服务项目',
        'url_navi1': '#',
        'url_navi2': '#',
    },
    # 公示信息
    'price': {
        'category': 'price',
        'father_category': 'publicity',
        'table_item': 'item',
        'table_file': 'file',
        'navi_sub': 'publicity-price',
        'title_page': '公示信息管理',
        'items_per_page': paging.manage_publicity_price,
        'thumb_width': 200,
        'thumb_height': 200,
        # 清单页面
        'title_content': '公示信息',
        'title_navi1': '公示信息',
        'title_navi2': '公示信息',
        'url_navi1': '#',
        'url_navi2': '#',
        # 添加页面
        'title_content_add': '添加公示信息',
        'title_navi1_add': '公示信息',
        'title_navi2_add': '公示信息',
        'url_navi1_add': '#',
        'url_navi2_add': '#',
        # 添加页面
        'title_content_edit': '编辑公示信息',
        'title_navi1_edit': '公示信息',
        'title_navi2_edit': '公示信息',
        'url_navi1_edit': '#',
        'url_navi2_edit': '#',

    },
    'hire': {
        'category': 'hire',
        'father_category': 'publicity',
        'table_item': 'item',
        'table_file': 'file',
        'navi_sub': 'publicity-hire',
        'title_page': '公示信息管理',
        'items_per_page': paging.manage_publicity_hire,
        'thumb_width': 200,
        'thumb_height': 200,
        # 清单页面
        'title_content': '招聘信息',
        'title_navi1': '公示信息',
        'title_navi2': '招聘信息',
        'url_navi1': '#',
        'url_navi2': '#',
        # 添加页面
        'title_content_add': '添加招聘信息',
        'title_navi1_add': '公示信息',
        'title_navi2_add': '招聘信息',
        'url_navi1_add': '#',
        'url_navi2_add': '#',
        # 添加页面
        'title_content_edit': '编辑招聘信息',
        'title_navi1_edit': '公示信息',
        'title_navi2_edit': '招聘信息',
        'url_navi1_edit': '#',
        'url_navi2_edit': '#',

    },
    # 新闻动态
    'news': {
        'category': 'news',
        'father_category': 'news',
        'table_item': 'item',
        'table_file': 'file',
        'navi_sub': 'news-news',
        'title_page': '新闻动态管理',
        'items_per_page': paging.manage_news_news,
        'thumb_width': 200,
        'thumb_height': 100,
        # 清单页面
        'title_content': '要点新闻',
        'title_navi1': '新闻动态',
        'title_navi2': '要点新闻',
        'url_navi1': '#',
        'url_navi2': '#',
        # 添加页面
        'title_content_add': '添加要点新闻',
        'title_navi1_add': '新闻动态',
        'title_navi2_add': '要点新闻',
        'url_navi1_add': '#',
        'url_navi2_add': '#',
        # 添加页面
        'title_content_edit': '编辑要点新闻',
        'title_navi1_edit': '新闻动态',
        'title_navi2_edit': '要点新闻',
        'url_navi1_edit': '#',
        'url_navi2_edit': '#',

    },
    'work': {
        'category': 'work',
        'father_category': 'news',
        'table_item': 'item',
        'table_file': 'file',
        'navi_sub': 'news-work',
        'title_page': '新闻动态管理',
        'items_per_page': paging.manage_news_work,
        'thumb_width': 200,
        'thumb_height': 100,
        # 清单页面
        'title_content': '工作动态',
        'title_navi1': '新闻动态',
        'title_navi2': '工作动态',
        'url_navi1': '#',
        'url_navi2': '#',
        # 添加页面
        'title_content_add': '添加工作动态',
        'title_navi1_add': '新闻动态',
        'title_navi2_add': '工作动态',
        'url_navi1_add': '#',
        'url_navi2_add': '#',
        # 添加页面
        'title_content_edit': '编辑工作动态',
        'title_navi1_edit': '新闻动态',
        'title_navi2_edit': '工作动态',
        'url_navi1_edit': '#',
        'url_navi2_edit': '#',

    },
    # 内部资料
    'certificate': {
        'category': 'certificate',
        'father_category': 'private',
        'table_item': 'item',
        'table_file': 'file',
        'navi_sub': 'private-certificate',
        'title_page': '内部资料管理',
        'items_per_page': paging.manage_private_certificate,
        'width_thumb': 200,
        'height_thumb': 200,
        'width_limit': 560,
        'height_limit': 560,
        'quality_limit': 65,
        'size_limit': 100,
        'compress_type': 4,     # 按高限压缩
        # 清单页面
        'title_content': '资质证书(全)',
        'title_navi1': '内部资料',
        'title_navi2': '资质证书',
        'url_navi1': '#',
        'url_navi2': '#',
    },
    'solution': {
        'category': 'solution',
        'father_category': 'private',
        'table_item': 'item',
        'table_file': 'file',
        'navi_sub': 'private-solution',
        'title_page': '内部资料管理',
        'items_per_page': paging.manage_private_solution,
        'thumb_width': 200,
        'thumb_height': 200,
        # 清单页面
        'title_content': '方案',
        'title_navi1': '内部资料',
        'title_navi2': '方案',
        'url_navi1': '#',
        'url_navi2': '#',
        # 添加页面
        'title_content_add': '添加方案',
        'title_navi1_add': '内部资料',
        'title_navi2_add': '方案',
        'url_navi1_add': '#',
        'url_navi2_add': '#',
        # 添加页面
        'title_content_edit': '编辑方案',
        'title_navi1_edit': '内部资料',
        'title_navi2_edit': '方案',
        'url_navi1_edit': '#',
        'url_navi2_edit': '#',

    },
    'standard': {
        'category': 'standard',
        'father_category': 'private',
        'table_item': 'item',
        'table_file': 'file',
        'navi_sub': 'private-standard',
        'title_page': '内部资料管理',
        'items_per_page': paging.manage_private_standard,
        'thumb_width': 200,
        'thumb_height': 200,
        # 清单页面
        'title_content': '规范标准',
        'title_navi1': '内部资料',
        'title_navi2': '规范标准',
        'url_navi1': '#',
        'url_navi2': '#',
        # 添加页面
        'title_content_add': '添加规范标准',
        'title_navi1_add': '内部资料',
        'title_navi2_add': '规范标准',
        'url_navi1_add': '#',
        'url_navi2_add': '#',
        # 添加页面
        'title_content_edit': '编辑规范标准',
        'title_navi1_edit': '内部资料',
        'title_navi2_edit': '规范标准',
        'url_navi1_edit': '#',
        'url_navi2_edit': '#',

    },
    # 案例展示
    'case': {
        'category': 'case',
        'father_category': 'case',
        'table_item': 'item',
        'table_file': 'file',
        'navi_sub': 'case-case',
        'title_page': '案例展示管理',
        'items_per_page': paging.manage_case,
        'thumb_width': 400,
        'thumb_height': 400,
        # 清单页面
        'title_content': '案例展示',
        'title_navi1': '案例展示',
        'title_navi2': '',
        'url_navi1': '#',
        'url_navi2': '#',
        # 添加页面
        'title_content_add': '添加案例展示',
        'title_navi1_add': '案例展示',
        'title_navi2_add': '',
        'url_navi1_add': '#',
        'url_navi2_add': '#',
        # 添加页面
        'title_content_edit': '编辑案例展示',
        'title_navi1_edit': '案例展示',
        'title_navi2_edit': '',
        'url_navi1_edit': '#',
        'url_navi2_edit': '#',

    },
}